### ISSUE TITLE
Добавить в проект уведомления

### ISSUE THREAD

**Issue by ZloyRob** [luisakisa/RN_test#15]
Использовать можно любую доступную библиотеку. НО ее выбор необходимо обосновать перед выполнением задачи.
## Цель
При запуске приложения должно генерироваться локальное уведомление, которое пользователь должен получить через 30 секунд. Текст уведомления произвольный.

**Comment by luisakisa** [comment]
Проведя анализ графика скачиваний(https://npmtrends.com/notifee-vs-react-native-fcm-vs-react-native-firebase-vs-react-native-notifications-vs-react-native-push-notification), я пришла к выводу, что лучше использовать react-native-push-notification. Меня также заинтересовала notifee, т.к. это относительно новая либа и она предоставляет более широкий набор функций, таких как настройка каналов уведомлений, настройка звуковых и визуальных эффектов и многое другое. Но для тестового примера достаточно базовых настроек.
